"""cravings last for now

Revision ID: 002f3c1248d4
Revises: a212ad3118c6
Create Date: 2025-03-18 20:11:15.073549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '002f3c1248d4'
down_revision: Union[str, None] = 'a212ad3118c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('craving_for_smoking', sa.Column('date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('craving_for_smoking', 'date')
    # ### end Alembic commands ###
