"""Add default parametr for email_confirmed

Revision ID: 0f3bc02233bf
Revises: 4798a1c3e12b
Create Date: 2025-02-22 23:28:47.868520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f3bc02233bf'
down_revision: Union[str, None] = '4798a1c3e12b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
