"""comments 4

Revision ID: 8e5e1fe3ac3d
Revises: 5e988a8ea9bb
Create Date: 2025-04-03 21:10:03.286087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e5e1fe3ac3d'
down_revision: Union[str, None] = '5e988a8ea9bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
