"""cravings v7

Revision ID: a212ad3118c6
Revises: 3755e52b821b
Create Date: 2025-03-18 17:39:10.990338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a212ad3118c6'
down_revision: Union[str, None] = '3755e52b821b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reasons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reason')
    )
    op.create_table('craving_for_smoking',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reason_id', sa.Integer(), nullable=False),
    sa.Column('is_smoking', sa.Boolean(), nullable=False),
    sa.Column('intensity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reason_id'], ['reasons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('craving_for_smoking')
    op.drop_table('reasons')
    # ### end Alembic commands ###
